server:
  port: 8081

#jwt
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
#logging
logging:
  level:
    tech.shunzi: INFO